USE AdPostingDB;
GO

DROP TABLE IF EXISTS Ad_Posted_Board;
DROP TABLE IF EXISTS Messages;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS Ad;
DROP TABLE IF EXISTS Board;
DROP TABLE IF EXISTS CollegeMember;
DROP TABLE IF EXISTS Person;
