USE AdPostingDB;
GO

DROP TABLE IF EXISTS Ad_Posted_Board;
DROP TABLE IF EXISTS Messages;
DROP TABLE IF EXISTS Ad;
DROP TABLE IF EXISTS Board;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS CollegeMember;
DROP TABLE IF EXISTS Person;
GO

USE master;
GO

IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'AdPostingDB')
BEGIN
    ALTER DATABASE AdPostingDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE AdPostingDB;
END
GO
